export const AUTH_COOKIE_NAME = 'refreshToken';

export const AUTH_ERROR_CODES = Object.freeze({
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INVALID_CODE: 'INVALID_CODE',
  CODE_EXPIRED: 'CODE_EXPIRED',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  PHONE_NUMBER_TAKEN: 'PHONE_NUMBER_TAKEN',
});
